<a href="https://colab.research.google.com/github/Slkandu/ML/blob/main/neuralnetwork.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:

df= pd.read_csv('/content/heart_attack_prediction_dataset_edit.csv')

In [ ]:
df.shape

(8763, 26)

In [ ]:
df.head()

,Patient ID,Age,Sex,Cholesterol,Blood Pressure,Heart Rate,Diabetes,Family History,Smoking,Obesity,...,Sedentary Hours Per Day,Income,BMI,Triglycerides,Physical Activity Days Per Week,Sleep Hours Per Day,Country,Continent,Hemisphere,Heart Attack Risk
0,BMW7812,67.0,m,208,158/88,72,0.0,0.0,1,0,...,6.615001,261404.0,31.251233,286,0,6.0,Argentina,South America,Southern Hemisphere,0
1,CZE1114,21.0,male,389,165/93,98,1.0,1.0,1,1,...,4.963459,285768.0,27.194973,235,1,7.0,Canada,North America,Northern Hemisphere,0
2,BNI9906,21.0,Female,324,174/99,72,1.0,0.0,0,0,...,9.463426,235282.0,28.176571,587,4,4.0,France,Europe,Northern Hemisphere,0
3,JLN3497,84.0,NaN,383,163/100,73,1.0,1.0,1,0,...,7.648981,125640.0,36.464704,378,3,4.0,Canada,North America,Northern Hemisphere,0
4,GFO8847,66.0,Male,318,91/88,93,NaN,1.0,1,1,...,1.514821,160555.0,21.809144,231,1,5.0,Thailand,Asia,Northern Hemisphere,0

In [ ]:

df = df.drop_duplicates(subset = 'Patient ID')

In [ ]:
import numpy as np
# Assuming 'df' is your DataFrame and contains numeric columns you want to process.
def remove_outliers_iqr(df, column):
    Q1 = df[column].quantile(0.25)
    Q3 = df[column].quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR
    df_filtered = df[(df[column] >= lower_bound) & (df[column] <= upper_bound)]
    return df_filtered

numeric_cols = df.select_dtypes(include=np.number).columns

for col in numeric_cols:
    df = remove_outliers_iqr(df, col)

In [ ]:
df.isnull().sum()

Patient ID                         0
Age                                0
Sex                                1
Cholesterol                        0
Blood Pressure                     0
Heart Rate                         0
Diabetes                           0
Family History                     0
Smoking                            0
Obesity                            0
Alcohol Consumption                0
Exercise Hours Per Week            0
Diet                               0
Previous Heart Problems            0
Medication Use                     0
Stress Level                       0
Sedentary Hours Per Day            0
Income                             0
BMI                                0
Triglycerides                      0
Physical Activity Days Per Week    0
Sleep Hours Per Day                0
Country                            0
Continent                          0
Hemisphere                         0
Heart Attack Risk                  0
dtype: int64

In [ ]:
# Create a list of columns to fill NA values
columns_to_fill = ['Age', 'Sedentary Hours Per Day','Income','Sleep Hours Per Day'] # Example columns, replace with your actual columns

# Fill NA values in specified columns with the mean of each column
for col in columns_to_fill:
    df[col] = df[col].fillna(df[col].mean())

In [ ]:
# Create a list of columns to fill NA values
columns_to_fill = ['Diabetes','Family History','Sex'] # Example columns, replace with your actual columns

# Fill NA values in specified columns with the mean of each column
for col in columns_to_fill:
  # Calculate the mode of the column
  mode_value = df[col].mode()[0]

  # Replace NaN values with the mode
  df[col].fillna(mode_value, inplace=True)

<ipython-input-96-f5789353b791>:10: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(mode_value, inplace=True)

In [ ]:
df.dtypes

Patient ID                          object
Age                                float64
Sex                                 object
Cholesterol                          int64
Blood Pressure                      object
Heart Rate                           int64
Diabetes                           float64
Family History                     float64
Smoking                              int64
Obesity                              int64
Alcohol Consumption                  int64
Exercise Hours Per Week            float64
Diet                                object
Previous Heart Problems              int64
Medication Use                       int64
Stress Level                         int64
Sedentary Hours Per Day            float64
Income                             float64
BMI                                float64
Triglycerides                        int64
Physical Activity Days Per Week      int64
Sleep Hours Per Day                float64
Country                             object
Continent                           object
Hemisphere                          object
Heart Attack Risk                    int64
dtype: object

In [ ]:
df.columns

Index(['Patient ID', 'Age', 'Sex', 'Cholesterol', 'Blood Pressure',
       'Heart Rate', 'Diabetes', 'Family History', 'Smoking', 'Obesity',
       'Alcohol Consumption', 'Exercise Hours Per Week', 'Diet',
       'Previous Heart Problems', 'Medication Use', 'Stress Level',
       'Sedentary Hours Per Day', 'Income', 'BMI', 'Triglycerides',
       'Physical Activity Days Per Week', 'Sleep Hours Per Day', 'Country',
       'Continent', 'Hemisphere', 'Heart Attack Risk'],
      dtype='object')

In [ ]:
category_cols = df.select_dtypes(include="object").columns

for col in category_cols:
    print(col)
    print(df[col].unique())

Patient ID
['BMW7812' 'CZE1114' 'JLN3497' ... 'MSV9918' 'XKA5925' 'EPE6801']
Sex
['m' 'male' 'Male' 'Female']
Blood Pressure
['158/88' '165/93' '163/100' ... '137/94' '94/76' '119/67']
Diet
['Average' 'Unhealthy' 'Healty' 'Healthy']
Country
['Argentina' 'Canada' 'Japan' 'Vietnam' 'China' 'Italy' 'Brazil'
 'Thailand' 'Spain' 'France' 'India' 'Nigeria' 'New Zealand'
 'United States' 'South Korea' 'Germany' 'Australia' 'South Africa'
 'Colombia' 'United Kingdom']
Continent
['South America' 'North America' 'Asia' 'Europe' 'Africa' 'Australia']
Hemisphere
['Southern Hemisphere' 'Northern Hemisphere']

In [ ]:
# replace 'Female' with female in sex column

dict1 = {'Female':'female','f':'female','m':'male','Male':'male'}

df['Sex'] = df['Sex'].replace(dict1)

# Calculate the mode of the column
mode_value = df['Sex'].mode()[0]

# Replace NaN values with the mode
df['Sex'].fillna(mode_value, inplace=True)

<ipython-input-100-9f5343b09dab>:11: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Sex'].fillna(mode_value, inplace=True)

In [ ]:
# replace 'Female' with female in sex column

dict2 = {'Healty':'Healthy','Unhelthy':'Unhealthy'}

df['Diet'] = df['Diet'].replace(dict1)

# Calculate the mode of the column
mode_value = df['Diet'].mode()[0]

# Replace NaN values with the mode
df['Diet'].fillna(mode_value, inplace=True)

<ipython-input-101-d48129dc25a0>:11: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Diet'].fillna(mode_value, inplace=True)

In [ ]:
# Splitting the column
split_cols = df['Blood Pressure'].str.split('/', expand=True)
split_cols.columns = ['Systolic', 'Diastolic']

# Convert to numeric (optional, for calculations)
df['Systolic'] = pd.to_numeric(split_cols['Systolic'])
df['Diastolic'] = pd.to_numeric(split_cols['Diastolic'])

In [ ]:
df.head()

,Patient ID,Age,Sex,Cholesterol,Blood Pressure,Heart Rate,Diabetes,Family History,Smoking,Obesity,...,BMI,Triglycerides,Physical Activity Days Per Week,Sleep Hours Per Day,Country,Continent,Hemisphere,Heart Attack Risk,Systolic,Diastolic
0,BMW7812,67.0,male,208,158/88,72,0.0,0.0,1,0,...,31.251233,286,0,6.0,Argentina,South America,Southern Hemisphere,0,158,88
1,CZE1114,21.0,male,389,165/93,98,1.0,1.0,1,1,...,27.194973,235,1,7.0,Canada,North America,Northern Hemisphere,0,165,93
3,JLN3497,84.0,male,383,163/100,73,1.0,1.0,1,0,...,36.464704,378,3,4.0,Canada,North America,Northern Hemisphere,0,163,100
6,WYV0966,90.0,male,358,102/73,84,0.0,0.0,1,0,...,28.885811,284,4,10.0,Canada,North America,Northern Hemisphere,1,102,73
7,XXM0972,84.0,male,220,131/68,107,0.0,0.0,1,1,...,22.221862,370,6,7.0,Japan,Asia,Northern Hemisphere,1,131,68

In [ ]:

encoded_data = pd.get_dummies(df, columns=[ 'Sex', 'Diet', 'Country', 'Continent', 'Hemisphere'], # Removed the trailing space from 'Smoking Status '
                              prefix=[ 'Sex', 'Diet', 'Country', 'Continent', 'Hemisphere']) # Removed the trailing space from 'Smoking Status '
df = encoded_data
print(df.head())

  Patient ID   Age  Cholesterol Blood Pressure  Heart Rate  Diabetes  \
0    BMW7812  67.0          208         158/88          72       0.0
1    CZE1114  21.0          389         165/93          98       1.0
3    JLN3497  84.0          383        163/100          73       1.0
6    WYV0966  90.0          358         102/73          84       0.0
7    XXM0972  84.0          220         131/68         107       0.0

   Family History  Smoking  Obesity  Alcohol Consumption  ...  \
0             0.0        1        0                    0  ...
1             1.0        1        1                    1  ...
3             1.0        1        0                    1  ...
6             0.0        1        0                    1  ...
7             0.0        1        1                    1  ...

   Country_United States  Country_Vietnam  Continent_Africa  Continent_Asia  \
0                  False            False             False           False
1                  False            False             False           False
3                  False            False             False           False
6                  False            False             False           False
7                  False            False             False            True

   Continent_Australia  Continent_Europe  Continent_North America  \
0                False             False                    False
1                False             False                     True
3                False             False                     True
6                False             False                     True
7                False             False                    False

   Continent_South America  Hemisphere_Northern Hemisphere  \
0                     True                           False
1                    False                            True
3                    False                            True
6                    False                            True
7                    False                            True

   Hemisphere_Southern Hemisphere
0                            True
1                           False
3                           False
6                           False
7                           False

[5 rows x 57 columns]

In [ ]:
import numpy as np

numerical_cols = df.select_dtypes(include=np.number).columns.tolist()
min_max_values = {}

for column in numerical_cols:
    min_value = df[column].min()
    max_value = df[column].max()
    min_max_values[column] = (min_value, max_value)

print(min_max_values)

{'Age': (18.0, 90.0), 'Cholesterol': (120, 400), 'Heart Rate': (40, 110), 'Diabetes': (0.0, 1.0), 'Family History': (0.0, 1.0), 'Smoking': (1, 1), 'Obesity': (0, 1), 'Alcohol Consumption': (0, 1), 'Exercise Hours Per Week': (0.002442348, 19.99870905), 'Previous Heart Problems': (0, 1), 'Medication Use': (0, 1), 'Stress Level': (1, 10), 'Sedentary Hours Per Day': (0.001263206, 11.99931341), 'Income': (20062.0, 299954.0), 'BMI': (18.00233658, 39.99721082), 'Triglycerides': (30, 800), 'Physical Activity Days Per Week': (0, 7), 'Sleep Hours Per Day': (4.0, 10.0), 'Heart Attack Risk': (0, 1), 'Systolic': (90, 180), 'Diastolic': (60, 110)}

In [ ]:
import json
with open('min_max_values.json', 'w') as json_file:
  json.dump(min_max_values, json_file)

In [ ]:
# Separate the features and target variable
X = df.drop(['Country','Patient ID','Blood Pressure','Heart Attack Risk'], axis=1)
# cols = ["Diabetes", "Cholesterol","Exercise Hours Per Week"]
# X = df[cols]
y = df['Heart Attack Risk']

KeyError: "['Country'] not found in axis"

In [ ]:
df['Heart Attack Risk'].value_counts()

Heart Attack Risk
0    5044
1    2806
Name: count, dtype: int64

In [ ]:
# split the data into train and test
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
from imblearn.over_sampling import SMOTE

# Convert y_train_top5 and y_train_rfe to pandas Series for easier manipulation
y_train = pd.Series(y_train)

# Display class distribution before oversampling
print('Before Oversampling for X_train:')
print(y_train.value_counts())

# Apply SMOTE for oversampling on the full training set
smote = SMOTE(random_state=42)

# Oversample X_train, y_train
X_train_smote, y_train_smote = smote.fit_resample(X_train, y_train)
# Display class distribution after oversampling
print('After Oversampling for X_train:')
print(y_train_smote.value_counts())

Before Oversampling for X_train:
Heart Attack Risk
0    4047
1    2233
Name: count, dtype: int64
After Oversampling for X_train:
Heart Attack Risk
1    4047
0    4047
Name: count, dtype: int64

In [ ]:
# prompt: deeplearning to predict the model

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

# Define the model
model = keras.Sequential([
    layers.Dense(128, activation='leaky_relu', input_shape=(X_train_smote.shape[1],)),
    layers.Dense(64, activation='leaky_relu'),
    layers.Dropout(0.3),  # Helps generalization
    layers.Dense(32, activation='leaky_relu'),
    layers.Dense(1, activation='sigmoid') # Changed the output layer to have 1 neuron
])

# Compile the model
model.compile(optimizer='adam',
              loss='binary_crossentropy',  # Binary cross-entropy for binary classification
              metrics=['accuracy'])

# Train the model
model.fit(X_train_smote, y_train_smote, epochs=50, batch_size=64, validation_split=0.2)

# Evaluate the model on the test set
loss, accuracy = model.evaluate(X_test, y_test)
print('Test accuracy:', accuracy)

# Make predictions on the test set
y_pred = model.predict(X_test)
y_pred_classes = (y_pred > 0.5).astype(int)

# You can further analyze the model's performance using metrics like precision, recall, F1-score, etc.
# You can also use techniques like confusion matrix to analyze the model's performance.

Epoch 1/50

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

102/102 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - accuracy: 0.5149 - loss: 5.5174 - val_accuracy: 0.0000e+00 - val_loss: 0.9136
Epoch 2/50
102/102 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5624 - loss: 0.7701 - val_accuracy: 0.4188 - val_loss: 0.7014
Epoch 3/50
102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.5739 - loss: 0.7057 - val_accuracy: 0.0000e+00 - val_loss: 0.8308
Epoch 4/50
102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.5787 - loss: 0.6994 - val_accuracy: 0.0000e+00 - val_loss: 0.8756
Epoch 5/50
102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.5802 - loss: 0.6976 - val_accuracy: 0.0000e+00 - val_loss: 1.0417
Epoch 6/50
102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.6146 - loss: 0.6750 - val_accuracy: 0.0000e+00 - val_loss: 1.0053
Epoch 7/50
102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.5950 - loss: 0.6887 - val_accuracy: 0.0000e+00 - val_loss: 0.7814
Epoch 8/50
102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.5947 - loss: 0.6869 - val_accuracy: 0.0000e+00 - val_loss: 1.0124
Epoch 9/50
102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.6202 - loss: 0.6721 - val_accuracy: 0.0000e+00 - val_loss: 1.0377
Epoch 10/50
102/102 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6117 - loss: 0.6779 - val_accuracy: 0.0000e+00 - val_loss: 0.8723
Epoch 11/50
102/102 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6140 - loss: 0.6760 - val_accuracy: 0.0000e+00 - val_loss: 1.0313
Epoch 12/50
102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.6053 - loss: 0.6781 - val_accuracy: 0.0000e+00 - val_loss: 1.0093
Epoch 13/50
102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.6233 - loss: 0.6702 - val_accuracy: 0.0000e+00 - val_loss: 1.2717
Epoch 14/50
102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.6129 - loss: 0.6761 - val_accuracy: 0.0000e+00 - val_loss: 0.9499
Epoch 15/50
102/102 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6239 - loss: 0.6716 - val_accuracy: 0.0000e+00 - val_loss: 1.0605
Epoch 16/50
102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.6114 - loss: 0.6775 - val_accuracy: 0.0000e+00 - val_loss: 1.2084
Epoch 17/50
102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.6201 - loss: 0.6683 - val_accuracy: 0.0000e+00 - val_loss: 1.1875
Epoch 18/50
102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.6031 - loss: 0.6792 - val_accuracy: 0.0000e+00 - val_loss: 0.9327
Epoch 19/50
102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.6170 - loss: 0.6721 - val_accuracy: 0.0000e+00 - val_loss: 0.9606
Epoch 20/50
102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.6166 - loss: 0.6690 - val_accuracy: 0.0000e+00 - val_loss: 0.8926
Epoch 21/50
102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.6072 - loss: 0.6740 - val_accuracy: 0.0000e+00 - val_loss: 0.9979
Epoch 22/50
102/102 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6006 - loss: 0.6765 - val_accuracy: 0.0000e+00 - val_loss: 0.8954
Epoch 23/50
102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.6177 - loss: 0.6712 - val_accuracy: 0.0000e+00 - val_loss: 1.0244
Epoch 24/50
102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.6261 - loss: 0.6664 - val_accuracy: 0.0000e+00 - val_loss: 0.8780
Epoch 25/50
102/102 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6138 - loss: 0.6709 - val_accuracy: 0.0000e+00 - val_loss: 1.0396
Epoch 26/50
102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.6257 - loss: 0.6638 - val_accuracy: 0.0000e+00 - val_loss: 1.1203
Epoch 27/50
102/102 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6183 - loss: 0.6705 - val_accuracy: 0.0000e+00 - val_loss: 0.9025
Epoch 28/50
102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.6054 - loss: 0.6726 - val_accuracy: 0.0000e+00 - val_loss: 0.9258
Epoch 29/50
102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.6187 - loss: 0.6677 - val_accuracy: 0.0000e+00 - val_loss: 1.2455
Epoch 30/50
102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.6213 - loss: 0.6688 - val_accuracy: 0.0000e+00 - val_loss: 1.0944
Epoch 31/50
102/102 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6263 - loss: 0.6645 - val_accuracy: 0.0000e+00 - val_loss: 0.9646
Epoch 32/50
102/102 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6201 - loss: 0.6682 - val_accuracy: 0.0000e+00 - val_loss: 1.0458
Epoch 33/50
102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.6134 - loss: 0.6719 - val_accuracy: 0.0000e+00 - val_loss: 1.1078
Epoch 34/50
102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.6119 - loss: 0.6713 - val_accuracy: 0.0000e+00 - val_loss: 1.0584
Epoch 35/50
102/102 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6184 - loss: 0.6663 - val_accuracy: 0.0000e+00 - val_loss: 1.0773
Epoch 36/50
102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.6149 - loss: 0.6690 - val_accuracy: 0.0000e+00 - val_loss: 1.0921
Epoch 37/50
102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.6247 - loss: 0.6634 - val_accuracy: 0.2205 - val_loss: 0.7724
Epoch 38/50
102/102 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6207 - loss: 0.6667 - val_accuracy: 0.0000e+00 - val_loss: 0.9673
Epoch 39/50
102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.6205 - loss: 0.6667 - val_accuracy: 0.0000e+00 - val_loss: 1.1613
Epoch 40/50
102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.6312 - loss: 0.6591 - val_accuracy: 0.0000e+00 - val_loss: 0.8323
Epoch 41/50
102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.6127 - loss: 0.6703 - val_accuracy: 0.0000e+00 - val_loss: 1.1693
Epoch 42/50
102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.6261 - loss: 0.6646 - val_accuracy: 0.5015 - val_loss: 0.6968
Epoch 43/50
102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.5965 - loss: 0.6817 - val_accuracy: 0.0000e+00 - val_loss: 1.1727
Epoch 44/50
102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.6103 - loss: 0.6735 - val_accuracy: 0.0000e+00 - val_loss: 0.9944
Epoch 45/50
102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.6214 - loss: 0.6651 - val_accuracy: 0.0000e+00 - val_loss: 1.0221
Epoch 46/50
102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.6229 - loss: 0.6645 - val_accuracy: 0.0000e+00 - val_loss: 0.8520
Epoch 47/50
102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.6045 - loss: 0.6779 - val_accuracy: 0.0000e+00 - val_loss: 1.0419
Epoch 48/50
102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.6188 - loss: 0.6695 - val_accuracy: 0.0000e+00 - val_loss: 0.9944
Epoch 49/50
102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.6125 - loss: 0.6690 - val_accuracy: 0.0000e+00 - val_loss: 0.9816
Epoch 50/50
102/102 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6234 - loss: 0.6640 - val_accuracy: 0.0000e+00 - val_loss: 1.0440
50/50 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6163 - loss: 0.6679
Test accuracy: 0.6350318193435669
50/50 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step